Repository Love-SOL/Love_SOL, pull requests merged in 2023-09, with the labels that each got.

#10 feat : PetController demo API 생성
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/PetController.java
Labels: enhancement

#13 feat: DB 유저 생성 쿼리문 작성
  data/DataUserCreate.sql
Labels: documentation

#16 Feat/be date management demo
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/CommentController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
Labels: enhancement

#29 Feat/be schedule create schedule
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/request/CreateScheduleRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/entity/ScheduleType.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/repository/UserRepository.java
Labels: enhancement

#31 Feat/be date log demo
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/request/UpdateImageDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/DateLog.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/Image.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageServiceImple.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionCode.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionController.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/NotExistDateLogException.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/NotExistImageException.java
Labels: enhancement

#33 Feat/be schedule update and delete schedule
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/request/UpdateScheduleRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/entity/Schedule.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
Labels: enhancement

#36 Feat/be cet crud
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/PetController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Pet.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/repository/PetRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetService.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetServiceImpl.java
Labels: enhancement

#39 Feat/be pet hotfix
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/PetController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/response/ResponsePetDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Pet.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetService.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetServiceImpl.java
Labels: bug

#40 Feat/be schedule get all schedule
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/DateLogForCalenderResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/DateLog.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/repository/DateLogRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/request/CreateScheduleRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/request/UpdateScheduleRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/response/CalenderResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/response/ScheduleResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/entity/Schedule.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/CreateUserAccountRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/entity/User.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/repository/UserRepository.java
  backend/src/main/java/com/ssafy/lovesol/global/config/WebConfig.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
Labels: enhancement

#42 fix: DateLog Entity LocalDateTime을 LocalDate로 수정
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/DateLog.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
Labels: bug

#45 Feat: 자동 입금 설정 수정, 조회 API 기능 개발(#9)
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/CoupleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/request/CoupleCreateRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserController.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/CreateUserAccountRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/UpdateUserAccountInfoDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/response/SampleResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/response/UserResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserService.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
  data/DDL.sql
Labels: enhancement

#46 feat: 특정 날짜 일정 조회 기능
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
Labels: enhancement

#47 Feat/be date log fix
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/DateLogResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/ImageResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/DateLog.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/Image.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/repository/ImageRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageServiceImple.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
Labels: bug

#50 fix: 데이트 일기 이미지 업데이트 오류 수정
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/request/UpdateImageDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageServiceImple.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/CreateUserAccountRequestDto.java
Labels: bug

#58 Feat/fe login start
  frontend/assets/bellicon.png
  frontend/assets/loginbackground.png
  frontend/assets/logincenterbox.png
  frontend/assets/loginclick.png
  frontend/assets/loginidinput.png
  frontend/assets/loginpasswordinput.png
  frontend/assets/personicon.png
  frontend/assets/simplepasswordbackground.png
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
  frontend/lib/main.dart
  frontend/lib/signUpPage.dart
  frontend/lib/simplePasswordPage.dart
  frontend/pubspec.yaml
Labels: enhancement

#59 Feat/fe signup start
  frontend/lib/homePage.dart
  frontend/lib/signUpPage.dart
Labels: enhancement

#60 feat: 간편비밀번호 페이지 추가
  frontend/lib/simplePasswordPage.dart
  frontend/pubspec.yaml
Labels: enhancement

#62 Feat/fe mainpage start
  frontend/lib/coupleSettingPage.dart
  frontend/lib/homePage.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement

#63 Feat/fe calendar start
  frontend/lib/calendarPage.dart
  frontend/lib/calendar_page.dart
  frontend/lib/colors.dart
  frontend/lib/weekdayswidget.dart
Labels: enhancement

#66 feat: comment table에 user_id 컬럼 추가
  data/DDL.sql
Labels: enhancement

#68 feat: 데이트 로그 댓글 작성자 ID 추가
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/request/InsertCommentRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/CommentResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/Comment.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/CommentServiceImpl.java
Labels: enhancement

#70 feat: 펫 경험치 증가 api 생성
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/PetController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/request/CreatePetRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/request/IncreasePetExpRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Pet.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
Labels: enhancement

#73 Feat/be entity create account and transaction
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Account.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Transaction.java
Labels: enhancement

#89 Feat/be account transfer and auth
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/request/TransferAuthRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/request/TransferRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Transaction.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/AccountRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserService.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionCode.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionController.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/NotExistAccountException.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/NotExistUserException.java
  backend/src/main/java/com/ssafy/lovesol/global/util/CommonHttpSend.java
Labels: enhancement

#94 Feat/fe pet start
  frontend/lib/calendarPage.dart
  frontend/lib/calendar_page.dart
  frontend/lib/petPage.dart
Labels: enhancement

#96 Feat/be schedule recent couple schedule
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
Labels: enhancement

#97 feat: 커플의 D-DAY 조회
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/CoupleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
Labels: enhancement

#98 Feat/be date log multipart file
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/request/InsertImageDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/ImageServiceImple.java
  backend/src/main/java/com/ssafy/lovesol/global/config/S3Config.java
  backend/src/main/resources/application.yml
Labels: enhancement

#102 feat: 로그인 API 연동
  frontend/lib/loginPage.dart
  frontend/pubspec.yaml
Labels: enhancement

#104 feat: 회원 가입 API 연동
  frontend/lib/loginPage.dart
  frontend/lib/signUpPage.dart
Labels: enhancement

#107 Feat/fe consumption start
  backend/src/main/resources/application.yml
  frontend/assets/bear1.gif
  frontend/assets/bear2.png
  frontend/assets/bear3.png
  frontend/assets/purple1.gif
  frontend/assets/purple2.png
  frontend/lib/calendarPage.dart
  frontend/lib/coupleSettingPage.dart
  frontend/lib/homePage.dart
  frontend/lib/petPage.dart
  frontend/lib/signUpPage.dart
  frontend/lib/simplePasswordPage.dart
  frontend/lib/weekdayswidget.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement

#109 Feat/be account get my accounts
  backend/build.gradle
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/response/GetUserAccountsResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Account.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
Labels: documentation

#111 feat: 내 명의 계좌 조회 연동
  frontend/lib/homePage.dart
Labels: enhancement

#113 FE: 1원이체,인증,회원가입 API 연결
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  frontend/lib/signUpPage.dart
Labels: enhancement

#117 BE: SMS 발송 기능
  backend/build.gradle
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/response/GetUserAccountsResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserController.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/PhoneNumberRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserService.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/global/util/SmsService.java
  backend/src/main/resources/application.yml
Labels: enhancement

#119 feat: 내 주 계좌 연동 후 화면에 표시
  frontend/lib/homePage.dart
Labels: enhancement

#121 feat: 간편 로그인 구현
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserController.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/SimpleLoginRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserService.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
Labels: enhancement

#126 Feat/be account get my accounts
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/response/GetUserAccountsResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Account.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/AccountRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
Labels: enhancement

#127 BE: 일정 작성 기능 수정
  backend/src/main/java/com/ssafy/lovesol/domain/couple/repository/CoupleRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserController.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/SimpleLoginRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/response/LoginResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/entity/User.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserService.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
Labels: enhancement

#129 Feat/fe save local data
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
  frontend/pubspec.yaml
Labels: enhancement

#135 Feat/fe calendar page detail
  frontend/lib/calendarPage.dart
  frontend/lib/calendar_page.dart
  frontend/lib/coupleSettingPage.dart
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
  frontend/lib/signUpPage.dart
  frontend/lib/weekdayswidget.dart
Labels: enhancement

#139 Feat/fe fcm recieve message
  frontend/android/app/build.gradle
  frontend/android/app/google-services.json
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/build.gradle
  frontend/lib/firebase_options.dart
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
  frontend/lib/main.dart
  frontend/lib/notification.dart
  frontend/lib/petPage.dart
  frontend/lib/signUpPage.dart
  frontend/pubspec.yaml
Labels: enhancement

#142 Feat: 자동 입금 이체 후 계좌 금액 정보 변경 구현
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Account.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserScheduler.java
Labels: enhancement

#144 Fix/fe login save
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
Labels: bug

#146 BE: 커플 D-DAY 관련 API
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/CoupleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/request/DDayRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/response/DDayResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Couple.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
  frontend/lib/calendarPage.dart
  frontend/lib/main.dart
Labels: enhancement

#147 Feat/fe fcm save
  frontend/lib/homePage.dart
  frontend/lib/loginPage.dart
  frontend/lib/main.dart
Labels: enhancement

#154 feat: 커플 DateLog 조회 기능
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/controller/DateLogController.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogService.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
Labels: enhancement

#160 fix: 파이어베이스 연동 주석 해제 및 notification 변경
  frontend/lib/main.dart
Labels: bug

#167 Refactor/pet get detail
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/PetController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/request/CreatePetRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Pet.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetService.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/dto/response/RecentCoupleScheduleResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/NotExistRecentCoupleScheduleException.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
  frontend/lib/homePage.dart
  frontend/lib/main.dart
Labels: enhancement

#170 FE: 커플 달력 화면 기능 수정 및 구현
  backend/src/main/java/com/ssafy/lovesol/domain/couple/dto/response/DDayResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/entity/Couple.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/controller/ScheduleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/entity/Schedule.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleService.java
  backend/src/main/java/com/ssafy/lovesol/domain/schedule/service/ScheduleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionCode.java
  backend/src/main/java/com/ssafy/lovesol/global/exception/ExceptionController.java
  frontend/lib/calendarPage.dart
  frontend/lib/homePage.dart
  frontend/lib/widget/DdayWidget.dart
  frontend/lib/widget/DiaryWidget.dart
Labels: enhancement

#173 BE: 계좌 거래 내역 조회 API
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/response/GetTransactionResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Transaction.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionServiceImpl.java
Labels: enhancement

#175 BE: 특정 년,월 계좌의 카테고리별 거래내역 조회 API
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/dto/response/GetTransactionByCategoryResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionServiceImpl.java
Labels: enhancement

#183 FE: 계좌별 거래내역,그래프 구현
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/TransactionServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/request/CreateUserAccountRequestDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/UserServiceImpl.java
  frontend/lib/authSimplePasswordPage.dart
  frontend/lib/homePage.dart
  frontend/lib/myAccountPage.dart
  frontend/lib/myConsumePage.dart
  frontend/lib/signUpPage.dart
  frontend/lib/widget/CalendarWidget.dart
Labels: enhancement

#188 FE: 화면 디테일 수정
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  frontend/lib/homePage.dart
  frontend/lib/myAccountPage.dart
  frontend/lib/signUpPage.dart
  frontend/lib/simplePasswordPage.dart
Labels: enhancement

#194 FE: 페이지 디테일 수정 및 API 연결 확인
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/entity/Transaction.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/CoupleController.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/controller/CoupleScheduler.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/UserScheduler.java
  backend/src/main/java/com/ssafy/lovesol/global/util/CommonHttpSend.java
  frontend/lib/homePage.dart
  frontend/lib/myAccountPage.dart
  frontend/lib/widget/CalendarWidget.dart
Labels: enhancement

#198 Feat/fe comment detail
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/CommentResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/Comment.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/CommentServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
  frontend/lib/widget/AlbumWidget.dart
Labels: enhancement

#203 FE: 러브 박스 계좌 조회
  backend/src/main/java/com/ssafy/lovesol/domain/bank/controller/AccountController.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountService.java
  backend/src/main/java/com/ssafy/lovesol/domain/bank/service/AccountServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
  frontend/lib/homePage.dart
Labels: enhancement

#205 Feat/fe couple create
  frontend/lib/coupleSettingPage.dart
Labels: duplicate, enhancement

#206 Fix: user ci 수정
  backend/src/main/java/com/ssafy/lovesol/global/util/InitDb.java
Labels: enhancement

#208 Feat: 알림 API 연결
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/PetServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/controller/NoticeController.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/dto/response/NoticeResDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/user/service/NoticeServiceImpl.java
  frontend/lib/calendarPage.dart
  frontend/lib/homePage.dart
  frontend/lib/widget/Appbar.dart
Labels: enhancement

#213 Fix: 계좌 거래내역 페이지 이동 수정
  backend/src/main/java/com/ssafy/lovesol/domain/bank/repository/TransactionRepository.java
  backend/src/main/java/com/ssafy/lovesol/domain/couple/service/CoupleServiceImpl.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/dto/response/DateLogForCalenderResponseDto.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/entity/DateLog.java
  backend/src/main/java/com/ssafy/lovesol/domain/datelog/service/DateLogServiceImpl.java
  frontend/lib/homePage.dart
  frontend/lib/myAccountPage.dart
  frontend/lib/widget/CalendarWidget.dart
  frontend/lib/widget/DiaryWidget.dart
Labels: enhancement
